const input=document.querySelector("#urlInput"),canvas=document.querySelector("#qrCanvas"),error=document.querySelector("#error"),previewUrl=document.querySelector("#previewUrl"),colorPicker=document.querySelector("#colorPicker"),colorValue=document.querySelector("#colorValue"),logoInput=document.querySelector("#logoInput"),removeLogo=document.querySelector("#removeLogo"),logoSize=document.querySelector("#logoSize"),sizeValue=document.querySelector("#sizeValue"),download=document.querySelector("#downloadBtn");let color="#000000",shape="square",logo=null,qr=null;
function normalize(v){v=v.trim();if(!/^https?:\/\//i.test(v))v="https://"+v;return v}
function valid(v){try{const u=new URL(v);return u.protocol==="http:"||u.protocol==="https:"}catch{return false}}
function render(){const raw=input.value.trim();if(!raw){qr=null;const c=canvas.getContext("2d");c.clearRect(0,0,canvas.width,canvas.height);previewUrl.textContent="Dán link để xem QR";return}const url=normalize(raw);if(!valid(url)){error.textContent="Link không hợp lệ.";return}error.textContent="";qr=new QRious({element:canvas,value:url,size:600,level:"H",background:"#fff",foreground:color});previewUrl.textContent=url;if(logo)drawLogo()}
function drawLogo(){if(!qr||!logo)return;const ctx=canvas.getContext("2d"),s=600*(Number(logoSize.value)/100),x=(600-s)/2,y=x,pad=s*.16;ctx.save();ctx.fillStyle="#fff";if(shape==="circle"){ctx.beginPath();ctx.arc(300,300,(s+pad*2)/2,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(300,300,s/2,0,Math.PI*2);ctx.clip()}else{const r=18;ctx.beginPath();ctx.roundRect(x-pad,y-pad,s+pad*2,s+pad*2,r);ctx.fill();ctx.beginPath();ctx.roundRect(x,y,s,s,r);ctx.clip()}ctx.drawImage(logo,x,y,s,s);ctx.restore()}
input.addEventListener("input",render);document.querySelectorAll("[data-color]").forEach(b=>b.addEventListener("click",()=>{color=b.dataset.color;colorPicker.value=color;colorValue.textContent=color;render()}));colorPicker.addEventListener("input",e=>{color=e.target.value;colorValue.textContent=color.toUpperCase();render()});
document.querySelectorAll("[data-shape]").forEach(b=>b.addEventListener("click",()=>{shape=b.dataset.shape;document.querySelectorAll("[data-shape]").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()}));
logoInput.addEventListener("change",e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{logo=img;render()};img.src=reader.result};reader.readAsDataURL(file)});
removeLogo.addEventListener("click",()=>{logo=null;logoInput.value="";render()});logoSize.addEventListener("input",()=>{sizeValue.textContent=logoSize.value+"%";render()});
download.addEventListener("click",()=>{if(!qr)return;const a=document.createElement("a");a.download="qrify-custom.png";a.href=canvas.toDataURL("image/png");a.click()});
